# Generated by Django 3.1 on 2020-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostTown', '0002_auto_20200819_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
